# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gui(object):
    def setupUi(self, gui):
        gui.setObjectName("gui")
        gui.resize(976, 628)
        gui.setMinimumSize(QtCore.QSize(976, 628))
        gui.setMaximumSize(QtCore.QSize(976, 628))
        self.centralwidget = QtWidgets.QWidget(gui)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 971, 601))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 969, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 971, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 10, 901, 571))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        gui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        self.menuAlgoritmos = QtWidgets.QMenu(self.menubar)
        self.menuAlgoritmos.setObjectName("menuAlgoritmos")
        gui.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(gui)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../srcjava/images/abrir.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../srcjava/images/abrir.gif"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action.setIcon(icon)
        self.action.setObjectName("action")
        self.actionAFND_AFD = QtWidgets.QAction(gui)
        self.actionAFND_AFD.setCheckable(True)
        self.actionAFND_AFD.setEnabled(True)
        self.actionAFND_AFD.setObjectName("actionAFND_AFD")
        self.actionMinimizar = QtWidgets.QAction(gui)
        self.actionMinimizar.setObjectName("actionMinimizar")
        self.actionEvaluar_expresion = QtWidgets.QAction(gui)
        self.actionEvaluar_expresion.setObjectName("actionEvaluar_expresion")
        self.action_2 = QtWidgets.QAction(gui)
        self.action_2.setPriority(QtWidgets.QAction.HighPriority)
        self.action_2.setObjectName("action_2")
        self.actionAbrir = QtWidgets.QAction(gui)
        self.actionAbrir.setMenuRole(QtWidgets.QAction.ApplicationSpecificRole)
        self.actionAbrir.setObjectName("actionAbrir")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuAlgoritmos.addAction(self.actionAFND_AFD)
        self.menuAlgoritmos.addAction(self.actionMinimizar)
        self.menuAlgoritmos.addAction(self.actionEvaluar_expresion)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuAlgoritmos.menuAction())

        self.retranslateUi(gui)
        QtCore.QMetaObject.connectSlotsByName(gui)

    def retranslateUi(self, gui):
        _translate = QtCore.QCoreApplication.translate
        gui.setWindowTitle(_translate("gui", "MainWindow"))
        self.menuArchivo.setTitle(_translate("gui", "Archivo"))
        self.menuEditar.setTitle(_translate("gui", "Editar"))
        self.menuHerramientas.setTitle(_translate("gui", "Herramientas"))
        self.menuAlgoritmos.setTitle(_translate("gui", "Algoritmos"))
        self.action.setText(_translate("gui", "Abrir"))
        self.actionAFND_AFD.setText(_translate("gui", "AFND=>AFD"))
        self.actionMinimizar.setText(_translate("gui", "Minimizar"))
        self.actionEvaluar_expresion.setText(_translate("gui", "Evaluar expresion"))
        self.action_2.setText(_translate("gui", "Abrir"))
        self.actionAbrir.setText(_translate("gui", "Abrir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gui = QtWidgets.QMainWindow()
    ui = Ui_gui()
    ui.setupUi(gui)
    gui.show()
    sys.exit(app.exec_())
