# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gui(object):
    def setupUi(self, gui):
        gui.setObjectName("gui")
        gui.resize(353, 519)
        self.centralwidget = QtWidgets.QWidget(gui)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 361, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 361, 491))
        self.widget.setObjectName("widget")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 351, 501))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(330, 0, 20, 491))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        gui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        self.menuAlgoritmos = QtWidgets.QMenu(self.menubar)
        self.menuAlgoritmos.setObjectName("menuAlgoritmos")
        gui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gui)
        self.statusbar.setObjectName("statusbar")
        gui.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(gui)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../srcjava/images/abrir.gif"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbrir.setIcon(icon)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionAFND_AFD = QtWidgets.QAction(gui)
        self.actionAFND_AFD.setObjectName("actionAFND_AFD")
        self.actionMinimizar = QtWidgets.QAction(gui)
        self.actionMinimizar.setObjectName("actionMinimizar")
        self.actionEvaluar_expresion = QtWidgets.QAction(gui)
        self.actionEvaluar_expresion.setObjectName("actionEvaluar_expresion")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuAlgoritmos.addAction(self.actionAFND_AFD)
        self.menuAlgoritmos.addAction(self.actionMinimizar)
        self.menuAlgoritmos.addAction(self.actionEvaluar_expresion)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuAlgoritmos.menuAction())

        self.retranslateUi(gui)
        QtCore.QMetaObject.connectSlotsByName(gui)

    def retranslateUi(self, gui):
        _translate = QtCore.QCoreApplication.translate
        gui.setWindowTitle(_translate("gui", "MainWindow"))
        self.menuArchivo.setTitle(_translate("gui", "Archivo"))
        self.menuEditar.setTitle(_translate("gui", "Editar"))
        self.menuHerramientas.setTitle(_translate("gui", "Herramientas"))
        self.menuAlgoritmos.setTitle(_translate("gui", "Algoritmos"))
        self.actionAbrir.setText(_translate("gui", "Abrir"))
        self.actionAFND_AFD.setText(_translate("gui", "AFND=>AFD"))
        self.actionMinimizar.setText(_translate("gui", "Minimizar"))
        self.actionEvaluar_expresion.setText(_translate("gui", "Evaluar expresion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gui = QtWidgets.QMainWindow()
    ui = Ui_gui()
    ui.setupUi(gui)
    gui.show()
    sys.exit(app.exec_())
